import fs from 'fs';
import path from 'path';
import AdmZip from 'adm-zip';
import { getDb, saveDbSync } from './db';
import { Server, ServerFile, ServerBackup, ServerDatabase, ServerActivity } from '../src/types';
import { dispatchDiscordNotification } from './discordService';

const SERVERS_DIR = path.join(process.cwd(), 'data', 'servers');

// In-memory console log buffer per server
const consoleBuffers: Record<string, string[]> = {};

function getConsoleBuffer(serverId: string): string[] {
  if (!consoleBuffers[serverId]) {
    consoleBuffers[serverId] = [
      `[${new Date().toLocaleTimeString()}] [AetherDaemon/INFO]: Server container initialized.`,
      `[${new Date().toLocaleTimeString()}] [AetherDaemon/INFO]: Resource limits applied: vCPU & RAM allocated successfully.`
    ];
  }
  return consoleBuffers[serverId];
}

export function appendConsoleLog(serverId: string, logLine: string) {
  const buf = getConsoleBuffer(serverId);
  const formatted = `[${new Date().toLocaleTimeString()}] ${logLine}`;
  buf.push(formatted);
  if (buf.length > 500) {
    buf.shift();
  }
}

export async function getServerConsoleLogs(serverId: string): Promise<string[]> {
  return getConsoleBuffer(serverId);
}

// Server Virtual Disk Directory Helper
export function getServerDir(serverId: string): string {
  const dir = path.join(SERVERS_DIR, serverId);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

// Ensure initial files exist on disk for a new server
export function initializeServerFiles(serverId: string, productCategory: string, software: string) {
  const dir = getServerDir(serverId);

  if (productCategory === 'minecraft') {
    const eulaPath = path.join(dir, 'eula.txt');
    if (!fs.existsSync(eulaPath)) {
      fs.writeFileSync(eulaPath, '# By changing the setting below to TRUE you are indicating your agreement to our EULA\neula=true\n');
    }

    const propPath = path.join(dir, 'server.properties');
    if (!fs.existsSync(propPath)) {
      fs.writeFileSync(propPath, [
        '# Minecraft server properties',
        '# Generated by AetherPanel',
        'server-port=25565',
        'gamemode=survival',
        'difficulty=easy',
        'pvp=true',
        'max-players=20',
        'motd=\\u00a7bAetherPanel \\u00a77- High Performance Minecraft Host',
        'online-mode=true',
        'allow-flight=false',
        'enable-command-block=true',
        'view-distance=10'
      ].join('\n'));
    }

    const pluginsDir = path.join(dir, 'plugins');
    if (!fs.existsSync(pluginsDir)) {
      fs.mkdirSync(pluginsDir, { recursive: true });
    }

    const worldDir = path.join(dir, 'world');
    if (!fs.existsSync(worldDir)) {
      fs.mkdirSync(worldDir, { recursive: true });
      fs.writeFileSync(path.join(worldDir, 'level.dat'), 'MOCK_WORLD_DATA');
    }
  } else if (productCategory === 'bot') {
    if (software.toLowerCase().includes('python')) {
      const botPy = path.join(dir, 'bot.py');
      if (!fs.existsSync(botPy)) {
        fs.writeFileSync(botPy, [
          'import discord',
          'import os',
          'from dotenv import load_dotenv',
          '',
          'load_dotenv()',
          'client = discord.Client(intents=discord.Intents.default())',
          '',
          '@client.event',
          'async def on_ready():',
          '    print(f"Logged in as {client.user} on AetherPanel!")',
          '',
          'client.run(os.getenv("DISCORD_TOKEN"))'
        ].join('\n'));
      }

      const reqPath = path.join(dir, 'requirements.txt');
      if (!fs.existsSync(reqPath)) {
        fs.writeFileSync(reqPath, 'discord.py>=2.3.2\npython-dotenv>=1.0.0\n');
      }
    } else {
      // Node.js Bot
      const indexJs = path.join(dir, 'index.js');
      if (!fs.existsSync(indexJs)) {
        fs.writeFileSync(indexJs, [
          'const { Client, GatewayIntentBits } = require("discord.js");',
          'require("dotenv").config();',
          '',
          'const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages] });',
          '',
          'client.once("ready", () => {',
          '  console.log(`[BOT] AetherPanel Discord Bot online as ${client.user.tag}!`);',
          '});',
          '',
          'client.on("interactionCreate", async interaction => {',
          '  if (!interaction.isChatInputCommand()) return;',
          '  if (interaction.commandName === "ping") {',
          '    await interaction.reply("Pong! Latency: " + client.ws.ping + "ms");',
          '  }',
          '});',
          '',
          'client.login(process.env.DISCORD_TOKEN || "MOCK_TOKEN");'
        ].join('\n'));
      }

      const pkgPath = path.join(dir, 'package.json');
      if (!fs.existsSync(pkgPath)) {
        fs.writeFileSync(pkgPath, JSON.stringify({
          name: 'aether-discord-bot',
          version: '1.0.0',
          description: 'Hosted on AetherPanel',
          main: 'index.js',
          scripts: {
            start: 'node index.js'
          },
          dependencies: {
            'discord.js': '^14.14.1',
            'dotenv': '^16.4.5'
          }
        }, null, 2));
      }
    }

    const envPath = path.join(dir, '.env');
    if (!fs.existsSync(envPath)) {
      fs.writeFileSync(envPath, 'DISCORD_TOKEN=your_bot_token_here\nPREFIX=!\nENVIRONMENT=production\nPORT=3000\n');
    }
  }
}

// Server Control Actions
export async function startServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  server.status = 'starting';
  saveDbSync();

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Launching server process container...`);
  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Allocated ${server.limits.ramMB}MB RAM, ${server.limits.cpuCores} CPU Cores.`);

  const prod = db.products.find(p => p.id === server.productId);
  const category = prod?.category || 'minecraft';

  initializeServerFiles(serverId, category, server.software);

  setTimeout(() => {
    if (category === 'minecraft') {
      appendConsoleLog(serverId, `[Server thread/INFO]: Loading Paper version 1.20.4-R0.1-SNAPSHOT (Java 21)`);
      appendConsoleLog(serverId, `[Server thread/INFO]: Preparing level "world"`);
      appendConsoleLog(serverId, `[Server thread/INFO]: Preparing start region for dimension minecraft:overworld`);
      appendConsoleLog(serverId, `[Server thread/INFO]: Time elapsed: 1400 ms`);
      appendConsoleLog(serverId, `[Server thread/INFO]: Done (2.108s)! For help, type "help"`);
      appendConsoleLog(serverId, `[AetherDaemon/SUCCESS]: Server is listening on ${server.primaryIp}:${server.primaryPort}`);
    } else {
      appendConsoleLog(serverId, `[Bot/INFO]: Initializing runtime environment (${server.software})...`);
      appendConsoleLog(serverId, `[Bot/INFO]: Executing startup command: ${server.software === 'Python' ? 'python3 bot.py' : 'node index.js'}`);
      appendConsoleLog(serverId, `[Bot/INFO]: [DISCORD] Gateway connected with 0ms delay!`);
      appendConsoleLog(serverId, `[AetherDaemon/SUCCESS]: Bot process is active and monitored 24/7.`);
    }

    server.status = 'running';
    server.cpuUsage = Math.min(25, Math.floor(Math.random() * 15 + 5));
    server.ramUsageMB = Math.floor(server.limits.ramMB * 0.35);
    saveDbSync();

    // Dispatch Discord Notification
    dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
      message: `Server '${server.name}' started successfully and is now running.`
    }).catch(err => console.error('[Discord] Start notification error:', err));
  }, 1200);

  return true;
}

export async function stopServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  server.status = 'stopping';
  saveDbSync();

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Sending SIGTERM graceful shutdown signal...`);

  setTimeout(() => {
    appendConsoleLog(serverId, `[Server thread/INFO]: Saving chunks for level 'world'...`);
    appendConsoleLog(serverId, `[Server thread/INFO]: Server thread stopped.`);
    appendConsoleLog(serverId, `[AetherDaemon/INFO]: Container stopped cleanly.`);

    server.status = 'stopped';
    server.cpuUsage = 0;
    server.ramUsageMB = 0;
    saveDbSync();

    // Dispatch Discord Notification
    dispatchDiscordNotification(serverId, 'SERVER_STOPPED', {
      message: `Server '${server.name}' has been stopped.`
    }).catch(err => console.error('[Discord] Stop notification error:', err));
  }, 1000);

  return true;
}

export async function restartServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (server) {
    dispatchDiscordNotification(serverId, 'SERVER_RESTARTED', {
      message: `Server '${server.name}' restart sequence initiated.`
    }).catch(err => console.error('[Discord] Restart notification error:', err));
  }
  await stopServer(serverId);
  setTimeout(async () => {
    await startServer(serverId);
  }, 1500);
  return true;
}

export async function reinstallServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  server.status = 'installing';
  saveDbSync();

  appendConsoleLog(serverId, `[AetherDaemon/WARN]: Wiping server filesystem and reinstalling base template...`);

  const dir = getServerDir(serverId);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  const prod = db.products.find(p => p.id === server.productId);
  initializeServerFiles(serverId, prod?.category || 'minecraft', server.software);

  setTimeout(() => {
    appendConsoleLog(serverId, `[AetherDaemon/SUCCESS]: Reinstallation completed successfully.`);
    server.status = 'stopped';
    saveDbSync();
  }, 1800);

  return true;
}

export async function sendServerCommand(serverId: string, command: string): Promise<string> {
  appendConsoleLog(serverId, `[UserCommand]: > ${command}`);

  const trimmed = command.trim();
  let response = '';

  if (trimmed === 'help') {
    response = 'Available commands: help, status, list, op <player>, say <msg>, tps, ping, reload';
  } else if (trimmed === 'tps') {
    response = 'TPS from last 1m, 5m, 15m: 20.0, 20.0, 19.98';
  } else if (trimmed.startsWith('say ')) {
    response = `[Server] ${trimmed.substring(4)}`;
  } else if (trimmed.startsWith('op ')) {
    response = `Made ${trimmed.substring(3)} a server operator`;
  } else if (trimmed === 'list') {
    response = 'There are 4 of max 20 players online: Alex_R, CraftMaster, Steve, Alex';
  } else if (trimmed === 'ping') {
    response = 'Pong! Latency: 14ms';
  } else {
    response = `Executed command: '${trimmed}'. Result OK.`;
  }

  appendConsoleLog(serverId, `[Server/Result]: ${response}`);
  return response;
}

export const sendServerConsoleInput = sendServerCommand;

// File Operations
export function listServerFiles(serverId: string, relPath: string = ''): ServerFile[] {
  const baseDir = getServerDir(serverId);
  const targetDir = path.join(baseDir, relPath);

  // Security check - path traversal prevention
  if (!targetDir.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetDir)) {
    return [];
  }

  const entries = fs.readdirSync(targetDir, { withFileTypes: true });
  return entries.map(entry => {
    const fullPath = path.join(targetDir, entry.name);
    const rel = path.relative(baseDir, fullPath).replace(/\\/g, '/');
    let stat = { size: 0, mtime: new Date() };
    try {
      stat = fs.statSync(fullPath);
    } catch (e) {}

    const ext = entry.isFile() ? path.extname(entry.name).toLowerCase() : undefined;

    return {
      name: entry.name,
      path: rel,
      size: entry.isFile() ? stat.size : 0,
      isDir: entry.isDirectory(),
      updatedAt: stat.mtime.toISOString(),
      extension: ext
    };
  }).sort((a, b) => (b.isDir ? 1 : 0) - (a.isDir ? 1 : 0) || a.name.localeCompare(b.name));
}

export function readServerFile(serverId: string, relPath: string): string {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('File not found');
  }

  return fs.readFileSync(targetPath, 'utf-8');
}

export function writeServerFile(serverId: string, relPath: string, content: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  const parentDir = path.dirname(targetPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, content, 'utf-8');
}

export function deleteServerItem(serverId: string, relPath: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (fs.existsSync(targetPath)) {
    fs.rmSync(targetPath, { recursive: true, force: true });
  }
}

export function createServerDirectory(serverId: string, relPath: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(targetPath, { recursive: true });
  }
}

export function renameServerItem(serverId: string, oldRelPath: string, newRelPath: string): void {
  const baseDir = getServerDir(serverId);
  const oldPath = path.join(baseDir, oldRelPath);
  const newPath = path.join(baseDir, newRelPath);

  if (!oldPath.startsWith(baseDir) || !newPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(oldPath)) {
    throw new Error('Source file or folder does not exist');
  }

  const parent = path.dirname(newPath);
  if (!fs.existsSync(parent)) {
    fs.mkdirSync(parent, { recursive: true });
  }

  fs.renameSync(oldPath, newPath);
}

export function compressServerItem(serverId: string, relPath: string): string {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('Item to compress not found');
  }

  const zip = new AdmZip();
  const stat = fs.statSync(targetPath);
  const zipFileName = `${path.basename(targetPath)}_${Date.now()}.zip`;
  const zipPath = path.join(path.dirname(targetPath), zipFileName);

  if (stat.isDirectory()) {
    zip.addLocalFolder(targetPath);
  } else {
    zip.addLocalFile(targetPath);
  }

  zip.writeZip(zipPath);
  return path.relative(baseDir, zipPath).replace(/\\/g, '/');
}

export function decompressServerItem(serverId: string, zipRelPath: string): void {
  const baseDir = getServerDir(serverId);
  const zipPath = path.join(baseDir, zipRelPath);

  if (!zipPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(zipPath)) {
    throw new Error('ZIP file not found');
  }

  const destDir = path.dirname(zipPath);
  const zip = new AdmZip(zipPath);
  zip.extractAllTo(destDir, true);
}

// Environment Variables (.env)
export function readServerEnv(serverId: string): Record<string, string> {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');
  const envMap: Record<string, string> = {};

  if (!fs.existsSync(envPath)) {
    return envMap;
  }

  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.substring(0, eqIdx).trim();
      const val = trimmed.substring(eqIdx + 1).trim();
      if (key) {
        envMap[key] = val;
      }
    }
  }

  return envMap;
}

export function writeServerEnv(serverId: string, envMap: Record<string, string>): void {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');

  const content = Object.entries(envMap)
    .map(([k, v]) => `${k.trim()}=${v}`)
    .join('\n');

  fs.writeFileSync(envPath, content, 'utf-8');
}

// Record Server Activity Audit
export async function recordServerActivity(
  serverId: string,
  userId: string,
  username: string,
  action: string,
  details: string
): Promise<ServerActivity> {
  const db = await getDb();
  const act: ServerActivity = {
    id: `act_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
    serverId,
    userId,
    username,
    action,
    details,
    createdAt: new Date().toISOString()
  };

  db.activities.unshift(act);
  saveDbSync();
  return act;
}

// Minecraft Plugins Helper
export interface MinecraftPluginInfo {
  filename: string;
  name: string;
  version?: string;
  size: number;
  isEnabled: boolean;
  updatedAt: string;
}

export function listMinecraftPlugins(serverId: string): MinecraftPluginInfo[] {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');

  if (!fs.existsSync(pluginsDir)) {
    fs.mkdirSync(pluginsDir, { recursive: true });
  }

  const files = fs.readdirSync(pluginsDir);
  const list: MinecraftPluginInfo[] = [];

  for (const f of files) {
    if (f.endsWith('.jar') || f.endsWith('.jar.disabled')) {
      const fullPath = path.join(pluginsDir, f);
      let stat = { size: 0, mtime: new Date() };
      try {
        stat = fs.statSync(fullPath);
      } catch (e) {}

      const isEnabled = !f.endsWith('.disabled');
      const cleanName = f.replace(/\.jar(\.disabled)?$/, '');

      list.push({
        filename: f,
        name: cleanName,
        version: '1.0.0',
        size: stat.size,
        isEnabled,
        updatedAt: stat.mtime.toISOString()
      });
    }
  }

  return list;
}

export function toggleMinecraftPlugin(serverId: string, filename: string): boolean {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');
  const currentPath = path.join(pluginsDir, filename);

  if (!fs.existsSync(currentPath)) {
    throw new Error('Plugin file not found');
  }

  if (filename.endsWith('.disabled')) {
    const newName = filename.replace(/\.disabled$/, '');
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return true; // Enabled
  } else if (filename.endsWith('.jar')) {
    const newName = `${filename}.disabled`;
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return false; // Disabled
  }

  return true;
}

