import fs from 'fs';
import path from 'path';
import { spawn, spawnSync, ChildProcess } from 'child_process';
import AdmZip from 'adm-zip';
import { getDb, saveDbSync } from './db';
import { Server, ServerFile, ServerBackup, ServerDatabase, ServerActivity } from '../src/types';
import { dispatchDiscordNotification } from './discordService';
import { buildBotStartupCommand } from '../src/lib/startup';

const SERVERS_DIR = path.join(process.cwd(), 'data', 'servers');

// In-memory active running child processes & telemetry map
interface ActiveProcessEntry {
  child?: ChildProcess;
  startedAt: Date;
  runnerType: 'minecraft' | 'bot_node' | 'bot_python' | 'custom';
  pid?: number;
}

const activeProcesses: Map<string, ActiveProcessEntry> = new Map();

// In-memory console log buffer per server
const consoleBuffers: Record<string, string[]> = {};

// Log listeners for live WebSocket streaming
type LogListener = (serverId: string, logLine: string) => void;
const logListeners: Set<LogListener> = new Set();

export function onConsoleLog(listener: LogListener): () => void {
  logListeners.add(listener);
  return () => logListeners.delete(listener);
}

// Server lifecycle status listeners for live WebSocket streaming
type StatusListener = (serverId: string, status: string, details?: any) => void;
const statusListeners: Set<StatusListener> = new Set();

export function onServerStatus(listener: StatusListener): () => void {
  statusListeners.add(listener);
  return () => statusListeners.delete(listener);
}

export function emitServerStatus(serverId: string, status: string, details?: any) {
  statusListeners.forEach((listener) => {
    try {
      listener(serverId, status, details);
    } catch {}
  });
}

export function clearConsoleBuffer(serverId: string) {
  delete consoleBuffers[serverId];
}

function getConsoleBuffer(serverId: string, isRunning: boolean = false): string[] {
  if (!consoleBuffers[serverId]) {
    if (!isRunning) {
      consoleBuffers[serverId] = [
        `[AetherDaemon]: Server is currently offline. Start the server to attach live console output.`
      ];
    } else {
      consoleBuffers[serverId] = [];
    }
  }
  return consoleBuffers[serverId];
}

export function appendConsoleLog(serverId: string, logLine: string) {
  const buf = getConsoleBuffer(serverId, true);
  // If buffer currently only has the offline placeholder message, replace it
  if (buf.length === 1 && buf[0].includes('Server is currently offline')) {
    buf.pop();
  }

  // Clean ANSI control characters if any
  const cleaned = logLine.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '').trimEnd();
  if (!cleaned) return;

  const lines = cleaned.split('\n');
  for (const l of lines) {
    if (!l.trim()) continue;
    const formatted = l.startsWith('[') ? l : `[${new Date().toLocaleTimeString()}] ${l}`;
    buf.push(formatted);

    // Notify active WebSocket listeners
    logListeners.forEach((listener) => {
      try {
        listener(serverId, formatted);
      } catch {}
    });
  }
  
  if (buf.length > 1000) {
    buf.splice(0, buf.length - 1000);
  }
}

export async function getServerConsoleLogs(serverId: string): Promise<string[]> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  const isRunning = server ? server.status === 'running' || server.status === 'starting' : false;
  return getConsoleBuffer(serverId, isRunning);
}

// Server Virtual Disk Directory Helper
export function getServerDir(serverId: string): string {
  const dir = path.join(SERVERS_DIR, serverId);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

// Ensure initial files exist on disk for a new server without overwriting existing files
export function initializeServerFiles(serverId: string, productCategory: string, software: string) {
  const dir = getServerDir(serverId);

  if (productCategory === 'minecraft') {
    const eulaPath = path.join(dir, 'eula.txt');
    if (!fs.existsSync(eulaPath)) {
      fs.writeFileSync(eulaPath, '# By changing the setting below to TRUE you are indicating your agreement to our EULA\neula=true\n');
    }

    const propPath = path.join(dir, 'server.properties');
    if (!fs.existsSync(propPath)) {
      fs.writeFileSync(propPath, [
        '# Minecraft server properties',
        '# Generated by AetherPanel',
        'server-port=25565',
        'gamemode=survival',
        'difficulty=easy',
        'pvp=true',
        'max-players=20',
        'motd=\\u00a7bAetherPanel \\u00a77- High Performance Minecraft Host',
        'online-mode=true',
        'allow-flight=false',
        'enable-command-block=true',
        'view-distance=10'
      ].join('\n'));
    }

    const pluginsDir = path.join(dir, 'plugins');
    if (!fs.existsSync(pluginsDir)) {
      fs.mkdirSync(pluginsDir, { recursive: true });
    }
  } else if (productCategory === 'bot') {
    // Empty bot server root: user uploads or creates application files
    // Ensure directory exists without generating fake application files
  }
}

export type InstallStatus = 'PIP_NOT_FOUND' | 'DEPENDENCY_INSTALL_FAILED' | 'DEPENDENCY_INSTALL_SUCCESS' | 'NO_REQUIREMENTS_FILE' | 'NO_PACKAGE_FILE' | 'STARTUP_FAILED';

// Bot Dependency Installation - Safe spawn without shell: true
export async function installServerDependencies(serverId: string): Promise<{ success: boolean; status: InstallStatus; output: string }> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) throw new Error('Server not found');

  const dir = getServerDir(serverId);
  const { runtime, executable } = buildBotStartupCommand(server, server.startup);

  appendConsoleLog(serverId, `[AetherInstaller/INFO]: Starting dependency installation for ${runtime}...`);

  if (runtime === 'python') {
    const reqPath = path.join(dir, 'requirements.txt');
    if (!fs.existsSync(reqPath)) {
      const msg = `[Installer/ERROR]: 'requirements.txt' not found. requirements.txt not found.`;
      appendConsoleLog(serverId, msg);
      return { success: false, status: 'NO_REQUIREMENTS_FILE', output: msg };
    }

    const pipCheck = spawnSync(executable, ['-m', 'pip', '--version'], { shell: false });
    if (pipCheck.status !== 0 || pipCheck.error) {
      const errorMsg = `[Installer/ERROR]: PIP_NOT_FOUND - Pip module is not available for interpreter '${executable}'.`;
      appendConsoleLog(serverId, errorMsg);
      return { success: false, status: 'PIP_NOT_FOUND', output: errorMsg };
    }
  } else {
    const pkgPath = path.join(dir, 'package.json');
    if (!fs.existsSync(pkgPath)) {
      const msg = `[Installer/INFO]: 'package.json' not found in server root. Skipping package installation.`;
      appendConsoleLog(serverId, msg);
      return { success: false, status: 'NO_PACKAGE_FILE', output: msg };
    }
  }

  return new Promise((resolve) => {
    let cmd = 'npm';
    let args = ['install'];

    if (runtime === 'python') {
      cmd = executable;
      args = ['-m', 'pip', 'install', '-r', 'requirements.txt'];
    } else if (runtime === 'bun') {
      cmd = 'bun';
      args = ['install'];
    }

    let output = '';
    const child = spawn(cmd, args, { cwd: dir, env: process.env, shell: false });

    child.stdout?.on('data', (data) => {
      const txt = data.toString();
      output += txt;
      appendConsoleLog(serverId, `[Installer]: ${txt}`);
    });

    child.stderr?.on('data', (data) => {
      const txt = data.toString();
      output += txt;
      appendConsoleLog(serverId, `[Installer/STDERR]: ${txt}`);
    });

    child.on('error', (err) => {
      appendConsoleLog(serverId, `[Installer/ERROR]: Failed to run ${cmd}: ${err.message}`);
      resolve({ success: false, status: 'DEPENDENCY_INSTALL_FAILED', output: output + '\n' + err.message });
    });

    child.on('close', (code) => {
      if (code === 0) {
        appendConsoleLog(serverId, `[Installer/SUCCESS]: Dependencies installed successfully (Exit Code 0).`);
        resolve({ success: true, status: 'DEPENDENCY_INSTALL_SUCCESS', output });
      } else {
        appendConsoleLog(serverId, `[Installer/WARN]: Dependency installation process finished with exit code: ${code}`);
        resolve({ success: false, status: 'DEPENDENCY_INSTALL_FAILED', output });
      }
    });
  });
}

import { checkJavaRuntime, getRecommendedJavaVersion } from './minecraftService';

// Remote command queue for servers running on remote nodes
const remoteCommandQueues: Map<string, string[]> = new Map();

// Track intentional stops/kills to prevent treating normal shutdowns as crashes
const intendedStops: Set<string> = new Set();
// Stable uptime timers map to reset crash counters after stable operation
const uptimeTimers: Map<string, NodeJS.Timeout> = new Map();
// Auto restart timers map
const autoRestartTimers: Map<string, NodeJS.Timeout> = new Map();

export function pullRemoteServerCommands(serverId: string): string[] {
  const queue = remoteCommandQueues.get(serverId) || [];
  remoteCommandQueues.delete(serverId);
  return queue;
}

export function queueRemoteServerCommand(serverId: string, command: string) {
  const q = remoteCommandQueues.get(serverId) || [];
  q.push(command);
  remoteCommandQueues.set(serverId, q);
}

// Preflight Resource & Validation Checks
export interface PreflightCheckResult {
  ok: boolean;
  code?: string;
  reason?: string;
}

export async function validateServerPreflight(serverId: string): Promise<PreflightCheckResult> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) {
    return { ok: false, code: 'SERVER_NOT_FOUND', reason: 'Server definition not found in database.' };
  }

  // 1. Check Node Status
  const node = db.nodes.find(n => n.id === server.nodeId);
  if (node) {
    if (node.isMaintenanceMode || node.status === 'maintenance') {
      return { ok: false, code: 'NODE_MAINTENANCE', reason: `Assigned node '${node.name}' is currently in maintenance mode.` };
    }
    if (node.status === 'offline' && !node.isLocalNode && node.id !== 'node_local') {
      return { ok: false, code: 'NODE_OFFLINE', reason: `Assigned node '${node.name}' is offline. Cannot initialize container.` };
    }
  }

  // 2. Check Allocation / Port Conflict
  const activeProcessesList = Array.from(activeProcesses.entries());
  for (const [otherServerId] of activeProcessesList) {
    if (otherServerId !== serverId) {
      const otherServer = db.servers.find(s => s.id === otherServerId);
      if (otherServer && otherServer.primaryPort === server.primaryPort && otherServer.nodeId === server.nodeId) {
        return { ok: false, code: 'PORT_CONFLICT', reason: `Primary port ${server.primaryPort} is currently bound by another active server (${otherServer.name}).` };
      }
    }
  }

  // 3. Check Software Runtime & Artifacts
  const prod = db.products.find(p => p.id === server.productId);
  const isBotSoftware = /bot|python|node|discord|telegram|js|bun/i.test(server.software) || /bot|python|node/i.test(server.productId || '');
  const category = prod?.category || (isBotSoftware ? 'bot' : 'minecraft');
  const dir = getServerDir(serverId);

  if (category === 'minecraft') {
    const reqJava = server.startup?.javaVersion || getRecommendedJavaVersion(server.version);
    const javaCheck = checkJavaRuntime(reqJava);
    if (!javaCheck.available) {
      if (javaCheck.code === 'JAVA_VERSION_MISMATCH') {
        return {
          ok: false,
          code: 'JAVA_VERSION_MISMATCH',
          required: javaCheck.required,
          detected: javaCheck.detected,
          version: server.version,
          reason: `Required Java: ${javaCheck.required}, Detected Java: ${javaCheck.detected || 'None'}. Required executable: ${javaCheck.path || 'Not Found'}. Server Version: ${server.version}`
        } as any;
      }
      return {
        ok: false,
        code: 'JAVA_RUNTIME_UNAVAILABLE',
        required: reqJava,
        detected: javaCheck.detected || null,
        version: server.version,
        reason: `Required Java: ${reqJava}, Detected Java: ${javaCheck.detected || 'None'}. Java Runtime is unavailable: ${javaCheck.message}`
      } as any;
    }

    const jarName = server.startup?.serverJar || 'server.jar';
    const serverJarPath = path.join(dir, jarName);
    if (!fs.existsSync(serverJarPath) || fs.statSync(serverJarPath).size < 1024) {
      return { ok: false, code: 'SERVER_JAR_MISSING', reason: `Server JAR artifact '${jarName}' is missing or corrupted in server root directory.` };
    }
  } else {
    // Bot Runtime
    const { startupFile, runtime, executable } = buildBotStartupCommand(server, server.startup);
    const scriptPath = path.join(dir, startupFile);
    if (!fs.existsSync(scriptPath)) {
      return { ok: false, code: 'NO_ENTRY_FILE', reason: `Startup failed. File: ${startupFile}. Reason: Startup file was not found.` };
    }

    const checkExec = spawnSync(executable, ['--version'], { shell: false });
    if (checkExec.status !== 0 && checkExec.status !== null && checkExec.error) {
      return { ok: false, code: 'RUNTIME_UNAVAILABLE', reason: `${runtime === 'python' ? 'Python' : runtime === 'bun' ? 'Bun' : 'Node.js'} runtime unavailable.` };
    }
  }

  return { ok: true };
}

// Read merged environment variables (.env file + server.envVars array + system params)
export function readServerMergedEnv(serverId: string, server: Server): Record<string, string> {
  const fileEnv = readServerEnv(serverId);
  const dbEnv: Record<string, string> = {};

  if (Array.isArray(server.envVars)) {
    for (const v of server.envVars) {
      if (v.isEnabled !== false && v.key) {
        dbEnv[v.key.trim()] = v.value || '';
      }
    }
  }

  const cleanEnv: Record<string, string> = {
    ...process.env as Record<string, string>,
    ...fileEnv,
    ...dbEnv,
    SERVER_ID: serverId,
    SERVER_NAME: server.name,
    SERVER_PORT: String(server.primaryPort),
    SERVER_IP: server.primaryIp || '0.0.0.0',
    SERVER_MEMORY_MB: String(server.limits.ramMB),
    SERVER_CPU_CORES: String(server.limits.cpuCores)
  };

  return cleanEnv;
}

// Server Control Actions
export async function startServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  // Clear any existing pending auto-restart timer
  const existingRestartTimer = autoRestartTimers.get(serverId);
  if (existingRestartTimer) {
    clearTimeout(existingRestartTimer);
    autoRestartTimers.delete(serverId);
  }

  if (activeProcesses.has(serverId)) {
    appendConsoleLog(serverId, `[AetherDaemon/WARN]: Server process is already running.`);
    return true;
  }

  server.status = 'starting';
  saveDbSync();
  emitServerStatus(serverId, 'starting');

  // Preflight validation
  const preflight = await validateServerPreflight(serverId);
  if (!preflight.ok) {
    appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Preflight validation failed: ${preflight.reason} (${preflight.code})`);
    server.status = 'error';
    if (!server.startup) server.startup = {};
    server.startup.lastCrashReason = `Preflight error: ${preflight.reason}`;
    saveDbSync();
    emitServerStatus(serverId, 'error', { error: preflight.reason, code: preflight.code });
    return false;
  }

  // Clear previous log buffer for a fresh session if starting
  consoleBuffers[serverId] = [];

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Initializing container sandbox & allocating limits (${server.limits.ramMB}MB RAM, ${server.limits.cpuCores} vCPU)...`);

  const prod = db.products.find(p => p.id === server.productId);
  const isBotSoftware = /bot|python|node|discord|telegram|js|bun/i.test(server.software) || /bot|python|node/i.test(server.productId || '');
  const category = prod?.category || (isBotSoftware ? 'bot' : 'minecraft');
  const dir = getServerDir(serverId);

  const cleanEnv = readServerMergedEnv(serverId, server);

  // Check if server is on a remote node
  const node = db.nodes.find(n => n.id === server.nodeId);
  const isRemote = (node && !node.isLocalNode && node.id !== 'node_local') || (server.nodeId && server.nodeId !== 'node_local');

  if (isRemote) {
    appendConsoleLog(serverId, `[AetherDaemon/INFO]: Dispatching startup command to remote node '${node?.name || server.nodeId}' daemon...`);
    queueRemoteServerCommand(serverId, 'START');
    server.status = 'starting';
    saveDbSync();
    emitServerStatus(serverId, 'starting');
    return true;
  }

  if (category === 'bot') {
    const { runtime, startupFile, executable, args, compiledCommand } = buildBotStartupCommand(server, server.startup);
    if (!server.startup) server.startup = {};
    server.startup.compiledCommand = compiledCommand;
    server.startup.entryFile = startupFile;

    if (runtime === 'python') {
      const reqPath = path.join(dir, 'requirements.txt');
      if (fs.existsSync(reqPath)) {
        appendConsoleLog(serverId, `[AetherDaemon/INFO]: Detected 'requirements.txt' in Python server root. Running dependency preflight check...`);
        const depRes = await installServerDependencies(serverId);
        if (depRes.status === 'PIP_NOT_FOUND') {
          appendConsoleLog(serverId, `[AetherDaemon/WARN]: PIP_NOT_FOUND - Pip module unavailable for interpreter '${executable}'. Proceeding to start application without installing packages.`);
        } else if (depRes.status === 'DEPENDENCY_INSTALL_FAILED') {
          appendConsoleLog(serverId, `[AetherDaemon/ERROR]: DEPENDENCY_INSTALL_FAILED - Failed installing requirements.txt. Aborting startup.`);
          server.status = 'error';
          if (!server.startup) server.startup = {};
          server.startup.lastCrashReason = 'DEPENDENCY_INSTALL_FAILED';
          saveDbSync();
          emitServerStatus(serverId, 'error', { error: 'DEPENDENCY_INSTALL_FAILED' });
          return false;
        }
      }
    }

    const scriptPath = path.join(dir, startupFile);
    if (!fs.existsSync(scriptPath)) {
      const errReason = `Startup failed. File: ${startupFile}. Reason: Startup file was not found.`;
      appendConsoleLog(serverId, `[AetherDaemon/ERROR]: ${errReason}`);
      server.status = 'error';
      if (!server.startup) server.startup = {};
      server.startup.lastCrashReason = errReason;
      saveDbSync();
      emitServerStatus(serverId, 'error', { error: errReason });
      return false;
    }

    if (runtime === 'python') {
      cleanEnv.PYTHONUNBUFFERED = '1';
    }

    try {
      intendedStops.delete(serverId);

      const child = spawn(executable, args, {
        cwd: dir,
        env: cleanEnv,
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: false
      });

      const entry: ActiveProcessEntry = {
        child,
        startedAt: new Date(),
        runnerType: runtime === 'python' ? 'bot_python' : 'bot_node',
        pid: child.pid
      };
      activeProcesses.set(serverId, entry);

      if (!server.startup) server.startup = {};
      server.startup.pid = child.pid;
      server.startup.lastStartedAt = new Date().toISOString();

      appendConsoleLog(serverId, `[AetherDaemon/INFO]: Bot process spawned (PID: ${child.pid}) running ${executable} ${args.join(' ')}`);

      child.stdout?.on('data', (chunk) => {
        appendConsoleLog(serverId, chunk.toString());
        if (server.status === 'starting') {
          server.status = 'running';
          server.cpuUsage = 1.2;
          server.ramUsageMB = runtime === 'python' ? 32 : 45;
          server.uptimeSeconds = 0;
          saveDbSync();
          emitServerStatus(serverId, 'running', { pid: child.pid });
          setupStableUptimeReset(serverId);
          dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
            message: `Bot '${server.name}' (${server.software}) started successfully and is now active.`
          }).catch(() => {});
        }
      });

      child.stderr?.on('data', (chunk) => {
        appendConsoleLog(serverId, `[STDERR]: ${chunk.toString()}`);
      });

      child.on('error', (err) => {
        appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Process spawn error: ${err.message}`);
        server.status = 'error';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
        emitServerStatus(serverId, 'error', { error: err.message });
      });

      child.on('exit', (code, signal) => {
        handleProcessExit(serverId, code, signal, child);
      });

      // Keep starting until verified or active for 1.5 seconds
      server.status = 'starting';
      server.uptimeSeconds = 0;
      saveDbSync();
      emitServerStatus(serverId, 'starting', { pid: child.pid });

      setTimeout(async () => {
        if (activeProcesses.has(serverId) && server.status === 'starting') {
          server.status = 'running';
          server.cpuUsage = 1.2;
          server.ramUsageMB = runtime === 'python' ? 32 : 45;
          server.uptimeSeconds = 0;
          saveDbSync();
          emitServerStatus(serverId, 'running', { pid: child.pid });
          setupStableUptimeReset(serverId);
          dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
            message: `Bot '${server.name}' (${server.software}) started successfully and is now active.`
          }).catch(() => {});
        }
      }, 1500);

      return true;
    } catch (err: any) {
      appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Failed to start bot process: ${err.message}`);
      server.status = 'error';
      saveDbSync();
      emitServerStatus(serverId, 'error', { error: err.message });
      return false;
    }
  } else {
    // Minecraft Server Runtime Runner
    const reqJava = server.startup?.javaVersion || getRecommendedJavaVersion(server.version);
    const javaCheck = checkJavaRuntime(reqJava);
    if (!javaCheck.available) {
      appendConsoleLog(serverId, `[Server thread/ERROR]: Java Runtime check failed! ${javaCheck.message}`);
      if (javaCheck.code === 'JAVA_VERSION_MISMATCH') {
        appendConsoleLog(serverId, `[Server thread/ERROR]: Required Java: ${javaCheck.required}, Detected Java: ${javaCheck.detected || 'None'}. Required executable: ${javaCheck.path || 'Not Found'}. Server Version: ${server.version}`);
      } else {
        appendConsoleLog(serverId, `[Server thread/ERROR]: JAVA_RUNTIME_UNAVAILABLE: Required Java ${reqJava} is not installed or available on this system.`);
      }
      server.status = 'error';
      saveDbSync();
      emitServerStatus(serverId, 'error', { 
        error: javaCheck.code || 'JAVA_RUNTIME_UNAVAILABLE',
        required: javaCheck.required || reqJava,
        detected: javaCheck.detected || null,
        version: server.version
      });
      return false;
    }

    const jarName = server.startup?.serverJar || 'server.jar';
    const serverJarPath = path.join(dir, jarName);
    if (!fs.existsSync(serverJarPath) || fs.statSync(serverJarPath).size < 100) {
      appendConsoleLog(serverId, `[Server thread/ERROR]: '${jarName}' artifact is missing or invalid in server root.`);
      appendConsoleLog(serverId, `[Server thread/INFO]: Please use the Reinstall function to download the official server JAR.`);
      server.status = 'error';
      saveDbSync();
      emitServerStatus(serverId, 'error', { error: `${jarName} missing` });
      return false;
    }

    // Sync assigned primary port into server.properties
    const propPath = path.join(dir, 'server.properties');
    if (fs.existsSync(propPath)) {
      let propContent = fs.readFileSync(propPath, 'utf8');
      propContent = propContent.replace(/server-port=\d+/, `server-port=${server.primaryPort}`);
      fs.writeFileSync(propPath, propContent, 'utf8');
    }

    const xmsMB = server.startup?.xmsMB || 128;
    const xmxMB = server.startup?.xmxMB || server.limits.ramMB;

    appendConsoleLog(serverId, `[Server thread/INFO]: Starting Minecraft engine (${server.software} ${server.version}) on Java ${javaCheck.installedVersion || 21}`);
    appendConsoleLog(serverId, `[Server thread/INFO]: Allocating heap: ${xmsMB}M initial, ${xmxMB}M max`);
    appendConsoleLog(serverId, `[Server thread/INFO]: Binding socket on ${server.primaryIp || '0.0.0.0'}:${server.primaryPort}`);

    try {
      intendedStops.delete(serverId);

      const executable = javaCheck.path || 'java';
      const args: string[] = [`-Xms${xmsMB}M`, `-Xmx${xmxMB}M`];

      // Custom JVM Flags
      if (server.startup?.jvmFlags) {
        const extraFlags = server.startup.jvmFlags.split(/\s+/).filter(Boolean);
        args.push(...extraFlags);
      }

      args.push('-jar', jarName);

      if (server.startup?.nogui !== false) {
        args.push('nogui');
      }

      if (server.startup?.customFlags) {
        const extraCustom = server.startup.customFlags.split(/\s+/).filter(Boolean);
        args.push(...extraCustom);
      }

      const compiledCmd = `${executable} ${args.join(' ')}`;
      if (!server.startup) server.startup = {};
      server.startup.compiledCommand = compiledCmd;

      const child = spawn(executable, args, {
        cwd: dir,
        env: cleanEnv,
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: false
      });

      const entry: ActiveProcessEntry = {
        child,
        startedAt: new Date(),
        runnerType: 'minecraft',
        pid: child.pid
      };
      activeProcesses.set(serverId, entry);

      if (!server.startup) server.startup = {};
      server.startup.pid = child.pid;
      server.startup.lastStartedAt = new Date().toISOString();

      child.stdout?.on('data', (chunk) => {
        const str = chunk.toString();
        appendConsoleLog(serverId, str);

        // Check startup confirmation signals
        if (server.status === 'starting') {
          const isReadySignal = 
            /Done \([0-9.]+s\)!/i.test(str) ||
            str.includes('For help, type "help"') ||
            str.includes('Timings Reset') ||
            str.includes('Listening on /') ||
            str.includes('Thread Query Listener started') ||
            str.includes('RCON running on');

          if (isReadySignal) {
            server.status = 'running';
            server.cpuUsage = 2.8;
            server.ramUsageMB = 480;
            server.uptimeSeconds = 0;
            saveDbSync();
            emitServerStatus(serverId, 'running', { pid: child.pid });
            setupStableUptimeReset(serverId);
            dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
              message: `Minecraft Server '${server.name}' (${server.software} ${server.version}) is now ONLINE and listening on ${server.primaryIp}:${server.primaryPort}.`
            }).catch(() => {});
          }
        }

        if (str.includes('java.lang.UnsupportedClassVersionError') || str.includes('UnsupportedClassVersionError')) {
          server.startup = server.startup || {};
          if (server.startup.lastCrashReason !== 'JAVA_VERSION_MISMATCH') {
            server.startup.lastCrashReason = 'JAVA_VERSION_MISMATCH';
            appendConsoleLog(serverId, `\n[AetherDaemon/DIAGNOSTIC]: ====================================================`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: CRITICAL: Minecraft failed to start because the selected Java runtime`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: is incompatible with this Minecraft version.`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: `);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Minecraft:      ${server.version}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Required:       Java ${reqJava}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Currently used:  Java ${javaCheck.installedVersion || 'Unknown'}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Action:         Switch to Java ${reqJava}.`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: ====================================================\n`);
            saveDbSync();
          }
        }
      });

      child.stderr?.on('data', (chunk) => {
        const str = chunk.toString();
        appendConsoleLog(serverId, `[STDERR]: ${str}`);
        if (str.includes('java.lang.UnsupportedClassVersionError') || str.includes('UnsupportedClassVersionError')) {
          server.startup = server.startup || {};
          if (server.startup.lastCrashReason !== 'JAVA_VERSION_MISMATCH') {
            server.startup.lastCrashReason = 'JAVA_VERSION_MISMATCH';
            appendConsoleLog(serverId, `\n[AetherDaemon/DIAGNOSTIC]: ====================================================`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: CRITICAL: Minecraft failed to start because the selected Java runtime`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: is incompatible with this Minecraft version.`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: `);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Minecraft:      ${server.version}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Required:       Java ${reqJava}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Currently used:  Java ${javaCheck.installedVersion || 'Unknown'}`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: Action:         Switch to Java ${reqJava}.`);
            appendConsoleLog(serverId, `[AetherDaemon/DIAGNOSTIC]: ====================================================\n`);
            saveDbSync();
          }
        }
      });

      child.on('error', (err) => {
        appendConsoleLog(serverId, `[Server thread/ERROR]: Process spawn error: ${err.message}`);
        server.status = 'error';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
        emitServerStatus(serverId, 'error', { error: err.message });
      });

      child.on('exit', (code, signal) => {
        handleProcessExit(serverId, code, signal, child);
      });

      // Keep server in 'starting' state until confirmed by logs or fallback after 20s
      server.status = 'starting';
      server.uptimeSeconds = 0;
      saveDbSync();
      emitServerStatus(serverId, 'starting', { pid: child.pid });

      setTimeout(async () => {
        if (activeProcesses.has(serverId) && server.status === 'starting') {
          server.status = 'running';
          server.cpuUsage = 2.8;
          server.ramUsageMB = 480;
          server.uptimeSeconds = 0;
          saveDbSync();
          emitServerStatus(serverId, 'running', { pid: child.pid });
          setupStableUptimeReset(serverId);
          dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
            message: `Minecraft Server '${server.name}' (${server.software} ${server.version}) is now active on ${server.primaryIp}:${server.primaryPort}.`
          }).catch(() => {});
        }
      }, 20000);

      return true;
    } catch (err: any) {
      appendConsoleLog(serverId, `[Server thread/ERROR]: Failed to start: ${err.message}`);
      server.status = 'error';
      saveDbSync();
      emitServerStatus(serverId, 'error', { error: err.message });
      return false;
    }
  }
}

// Stable Uptime Tracker: Reset crash count after continuous stable execution
function setupStableUptimeReset(serverId: string) {
  const existing = uptimeTimers.get(serverId);
  if (existing) clearTimeout(existing);

  const timer = setTimeout(async () => {
    try {
      const db = await getDb();
      const server = db.servers.find(s => s.id === serverId);
      if (server && server.status === 'running' && server.startup) {
        if ((server.startup.crashCount || 0) > 0) {
          appendConsoleLog(serverId, `[AetherDaemon/INFO]: Server has operated stably for 5 minutes. Resetting crash counter to 0.`);
          server.startup.crashCount = 0;
          saveDbSync();
        }
      }
    } catch {}
  }, 300000); // 5 minutes

  uptimeTimers.set(serverId, timer);
}

// Process Exit & Crash Handler with Auto-Restart Policies
async function handleProcessExit(serverId: string, code: number | null, signal: string | null, exitedChild?: ChildProcess) {
  const currentEntry = activeProcesses.get(serverId);
  // If another process was already spawned for this server, ignore stale exit event
  if (currentEntry && exitedChild && currentEntry.child !== exitedChild) {
    return;
  }

  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return;

  activeProcesses.delete(serverId);
  const uptimeTimer = uptimeTimers.get(serverId);
  if (uptimeTimer) {
    clearTimeout(uptimeTimer);
    uptimeTimers.delete(serverId);
  }

  if (!server.startup) server.startup = {};
  server.startup.pid = undefined;
  server.startup.lastStoppedAt = new Date().toISOString();
  server.cpuUsage = 0;
  server.ramUsageMB = 0;

  if (server.startup?.lastCrashReason === 'JAVA_VERSION_MISMATCH') {
    appendConsoleLog(serverId, `[AetherDaemon/CRASH]: java.lang.UnsupportedClassVersionError detected! The Minecraft server jar requires a newer Java version than currently configured. Auto-recovery suspended to prevent endless crash loops.`);
    server.status = 'error';
    saveDbSync();
    emitServerStatus(serverId, 'error', { 
      error: 'JAVA_VERSION_MISMATCH',
      required: 21,
      detected: 17,
      version: server.version
    });
    return;
  }

  const isIntended = intendedStops.has(serverId);
  intendedStops.delete(serverId);

  if (isIntended || (code === 0 && !signal)) {
    // Normal graceful stop
    appendConsoleLog(serverId, `[AetherDaemon/INFO]: Process terminated cleanly (Exit Code: ${code ?? 0}, Signal: ${signal ?? 'NONE'}).`);
    server.status = 'stopped';
    saveDbSync();
    emitServerStatus(serverId, 'stopped', { exitCode: code, signal });
    return;
  }

  // Process Crashed / Terminated Abnormally
  appendConsoleLog(serverId, `[AetherDaemon/CRASH]: Process terminated unexpectedly with Exit Code ${code} (Signal: ${signal || 'NONE'}).`);

  server.startup.lastCrashAt = new Date().toISOString();
  server.startup.lastCrashReason = `Exit code ${code}${signal ? `, Signal ${signal}` : ''}`;
  server.startup.crashCount = (server.startup.crashCount || 0) + 1;

  const restartPolicy = server.startup.autoRestartPolicy || (server.startup.restartOnCrash === true ? 'on_crash' : 'never');
  const shouldRestart = server.startup.restartOnCrash === true && (restartPolicy === 'always' || (restartPolicy === 'on_crash' && code !== 0));
  const maxRestarts = server.startup.maxCrashRestarts ?? 5;
  const delaySec = server.startup.crashRestartDelaySeconds ?? 5;

  if (shouldRestart && server.startup.crashCount <= maxRestarts) {
    appendConsoleLog(serverId, `[AetherDaemon/CRASH]: Auto-restart policy '${restartPolicy}' triggered. Attempt ${server.startup.crashCount}/${maxRestarts} in ${delaySec}s...`);
    server.status = 'crashed';
    saveDbSync();
    emitServerStatus(serverId, 'crashed', { exitCode: code, signal, willRestart: true, retryIn: delaySec });

    const restartTimer = setTimeout(async () => {
      appendConsoleLog(serverId, `[AetherDaemon/RECOVERY]: Executing auto-restart attempt #${server.startup?.crashCount}...`);
      await startServer(serverId);
    }, delaySec * 1000);

    autoRestartTimers.set(serverId, restartTimer);
  } else {
    if (server.startup.crashCount > maxRestarts) {
      appendConsoleLog(serverId, `[AetherDaemon/CRASH]: Maximum auto-restart limit (${maxRestarts}) reached. Auto-recovery suspended.`);
    }
    server.status = 'stopped';
    saveDbSync();
    emitServerStatus(serverId, 'stopped', { exitCode: code, signal, willRestart: false });
  }
}

export async function stopServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  // Clear any scheduled auto-restart
  const pendingRestart = autoRestartTimers.get(serverId);
  if (pendingRestart) {
    clearTimeout(pendingRestart);
    autoRestartTimers.delete(serverId);
  }

  intendedStops.add(serverId);

  // Check if remote node server
  const node = db.nodes.find(n => n.id === server.nodeId);
  const isRemote = (node && !node.isLocalNode && node.id !== 'node_local') || (server.nodeId && server.nodeId !== 'node_local');
  if (isRemote) {
    queueRemoteServerCommand(serverId, 'STOP');
    server.status = 'stopping';
    saveDbSync();
    emitServerStatus(serverId, 'stopping');
    return true;
  }

  const entry = activeProcesses.get(serverId);
  if (!entry) {
    server.status = 'stopped';
    server.cpuUsage = 0;
    server.ramUsageMB = 0;
    server.uptimeSeconds = 0;
    if (server.startup) server.startup.pid = undefined;
    saveDbSync();
    emitServerStatus(serverId, 'stopped');
    return true;
  }

  server.status = 'stopping';
  saveDbSync();
  emitServerStatus(serverId, 'stopping');

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Sending graceful shutdown signal (SIGTERM)...`);

  if (entry.child) {
    try {
      if (entry.child.stdin && entry.child.stdin.writable) {
        entry.child.stdin.write('stop\n');
      }
      entry.child.kill('SIGTERM');

      // Escalate to SIGKILL if still alive after 3.5s
      setTimeout(() => {
        if (activeProcesses.has(serverId)) {
          appendConsoleLog(serverId, `[AetherDaemon/WARN]: Process did not exit cleanly within timeout. Escalating to SIGKILL...`);
          try {
            entry.child?.kill('SIGKILL');
          } catch {}
          activeProcesses.delete(serverId);
        }
      }, 3500);
    } catch {}
  }

  activeProcesses.delete(serverId);

  server.status = 'stopped';
  server.cpuUsage = 0;
  server.ramUsageMB = 0;
  server.uptimeSeconds = 0;
  if (!server.startup) server.startup = {};
  server.startup.pid = undefined;
  server.startup.lastStoppedAt = new Date().toISOString();
  saveDbSync();
  emitServerStatus(serverId, 'stopped');

  dispatchDiscordNotification(serverId, 'SERVER_STOPPED', {
    message: `Server '${server.name}' has been stopped.`
  }).catch(() => {});

  return true;
}

export async function killServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  // Clear any scheduled auto-restart
  const pendingRestart = autoRestartTimers.get(serverId);
  if (pendingRestart) {
    clearTimeout(pendingRestart);
    autoRestartTimers.delete(serverId);
  }

  intendedStops.add(serverId);

  // Check if remote node server
  const node = db.nodes.find(n => n.id === server.nodeId);
  const isRemote = (node && !node.isLocalNode && node.id !== 'node_local') || (server.nodeId && server.nodeId !== 'node_local');
  if (isRemote) {
    queueRemoteServerCommand(serverId, 'KILL');
    server.status = 'stopped';
    server.cpuUsage = 0;
    server.ramUsageMB = 0;
    saveDbSync();
    emitServerStatus(serverId, 'stopped');
    return true;
  }

  appendConsoleLog(serverId, `[AetherDaemon/WARN]: Immediate SIGKILL force-termination initiated by administrator.`);

  const entry = activeProcesses.get(serverId);
  if (entry && entry.child) {
    try {
      entry.child.kill('SIGKILL');
    } catch {}
  }

  activeProcesses.delete(serverId);

  server.status = 'stopped';
  server.cpuUsage = 0;
  server.ramUsageMB = 0;
  server.uptimeSeconds = 0;
  if (!server.startup) server.startup = {};
  server.startup.pid = undefined;
  server.startup.lastStoppedAt = new Date().toISOString();
  saveDbSync();
  emitServerStatus(serverId, 'stopped');

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Server process container killed and resources freed.`);

  return true;
}

export async function restartServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (server) {
    dispatchDiscordNotification(serverId, 'SERVER_RESTARTED', {
      message: `Server '${server.name}' restart sequence initiated.`
    }).catch(() => {});
  }
  emitServerStatus(serverId, 'restarting');
  await stopServer(serverId);
  await new Promise(r => setTimeout(r, 400));
  return await startServer(serverId);
}

// Panel Boot State Reconciliation & Auto-Start on Boot
export async function reconcileServerStatesOnBoot(): Promise<void> {
  console.log('[AETHERPANEL LIFECYCLE] Reconciling server states and executing boot recovery...');
  try {
    const db = await getDb();
    let modified = false;

    for (const server of db.servers) {
      const node = db.nodes.find(n => n.id === server.nodeId);
      const isLocal = !node || node.isLocalNode || node.id === 'node_local';

      if (isLocal) {
        // If status is marked running in DB but we just booted fresh without active process
        if (server.status === 'running' || server.status === 'starting') {
          let isActuallyAlive = false;
          if (server.startup?.pid) {
            try {
              process.kill(server.startup.pid, 0); // Check if PID exists
              isActuallyAlive = true;
            } catch {
              isActuallyAlive = false;
            }
          }

          if (!isActuallyAlive) {
            server.status = 'stopped';
            server.cpuUsage = 0;
            server.ramUsageMB = 0;
            if (server.startup) server.startup.pid = undefined;
            modified = true;
          }
        }

        // Check auto-start on boot
        if (server.startup?.autoStartOnBoot && server.status === 'stopped') {
          console.log(`[BOOT RECOVERY] Auto-starting server '${server.name}' (${server.id})...`);
          startServer(server.id).catch(err => {
            console.error(`[BOOT RECOVERY] Failed to auto-start server ${server.id}:`, err);
          });
        }
      }
    }

    if (modified) {
      saveDbSync();
    }
  } catch (err) {
    console.error('[AETHERPANEL LIFECYCLE] Boot reconciliation error:', err);
  }
}

// Auto-Start on Remote Node Reconnection
export async function handleNodeReconnect(nodeId: string): Promise<void> {
  try {
    const db = await getDb();
    const nodeServers = db.servers.filter(s => s.nodeId === nodeId);

    for (const server of nodeServers) {
      if (server.startup?.autoStartOnNodeReconnect && server.status === 'stopped') {
        console.log(`[NODE RECONNECT] Triggering auto-start for server '${server.name}' on reconnected node '${nodeId}'...`);
        startServer(server.id).catch(err => {
          console.error(`[NODE RECONNECT] Error starting server ${server.id}:`, err);
        });
      }
    }
  } catch (err) {
    console.error('[NODE RECONNECT] Error handling node reconnect:', err);
  }
}

export async function reinstallServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  await stopServer(serverId);

  server.status = 'installing';
  saveDbSync();
  emitServerStatus(serverId, 'installing');

  appendConsoleLog(serverId, `[AetherDaemon/WARN]: Wiping server filesystem and reinstalling fresh base template...`);

  const dir = getServerDir(serverId);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  const prod = db.products.find(p => p.id === server.productId);
  initializeServerFiles(serverId, prod?.category || 'minecraft', server.software);

  setTimeout(() => {
    appendConsoleLog(serverId, `[AetherDaemon/SUCCESS]: Reinstallation completed successfully. Ready to start.`);
    server.status = 'stopped';
    saveDbSync();
    emitServerStatus(serverId, 'stopped');
  }, 1200);

  return true;
}

export async function sendServerCommand(serverId: string, command: string): Promise<string> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);

  if (!server) {
    const errorMsg = 'Server not found.';
    return errorMsg;
  }

  // Check if server is running on a remote node
  const node = db.nodes.find(n => n.id === server.nodeId);
  const isRemote = (node && !node.isLocalNode && node.id !== 'node_local') || (server.nodeId && server.nodeId !== 'node_local');

  if (isRemote) {
    if (server.status !== 'running') {
      const errorMsg = 'Server is offline. Start the server to send commands.';
      appendConsoleLog(serverId, `[UserCommand/ERROR]: > ${command} (Failed: ${errorMsg})`);
      return errorMsg;
    }
    appendConsoleLog(serverId, `[UserCommand]: > ${command}`);
    queueRemoteServerCommand(serverId, command);
    return `Dispatched command '${command}' to remote node daemon for server ${serverId}.`;
  }

  const entry = activeProcesses.get(serverId);

  if (server.status !== 'running' || !entry) {
    const errorMsg = 'Server is offline. Start the server to send commands.';
    appendConsoleLog(serverId, `[UserCommand/ERROR]: > ${command} (Failed: ${errorMsg})`);
    return errorMsg;
  }

  appendConsoleLog(serverId, `[UserCommand]: > ${command}`);

  if (entry.child && entry.child.stdin && entry.child.stdin.writable) {
    try {
      entry.child.stdin.write(`${command}\n`);
      return `Sent '${command}' to running process stdin.`;
    } catch (err: any) {
      appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Stdin write failure: ${err.message}`);
      return `Failed to write to stdin: ${err.message}`;
    }
  }

  return `Command dispatched.`;
}

export const sendServerConsoleInput = sendServerCommand;

/**
 * Resolves and sanitizes a relative path within a server's root directory, preventing directory traversal.
 */
export function safePath(serverId: string, relPath: string = ''): string {
  const baseDir = path.resolve(getServerDir(serverId));
  const sanitized = (relPath || '').replace(/\0/g, '');
  const cleaned = path.normalize(sanitized).replace(/^(\.\.[\/\\])+/, '');
  const resolved = path.resolve(baseDir, '.' + (cleaned.startsWith('/') ? cleaned : '/' + cleaned));

  if (resolved !== baseDir && !resolved.startsWith(baseDir + path.sep)) {
    return baseDir;
  }
  return resolved;
}

// File Operations
export function listServerFiles(serverId: string, relPath: string = ''): ServerFile[] {
  const baseDir = path.resolve(getServerDir(serverId));
  if (relPath && relPath !== '/' && relPath !== '.') {
    const rawTarget = path.resolve(baseDir, relPath.replace(/\0/g, ''));
    if (rawTarget !== baseDir && !rawTarget.startsWith(baseDir + path.sep)) {
      throw new Error('Access denied: Outside server root directory');
    }
  }
  const targetDir = safePath(serverId, relPath);

  // Security check - path traversal prevention
  if (targetDir !== baseDir && !targetDir.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetDir)) {
    return [];
  }

  const entries = fs.readdirSync(targetDir, { withFileTypes: true });
  return entries.map(entry => {
    const fullPath = path.join(targetDir, entry.name);
    const rel = path.relative(baseDir, fullPath).replace(/\\/g, '/');
    let stat = { size: 0, mtime: new Date(), mode: 0o644 };
    try {
      stat = fs.statSync(fullPath);
    } catch (e) {}

    const ext = entry.isFile() ? path.extname(entry.name).toLowerCase() : undefined;

    return {
      name: entry.name,
      path: rel,
      size: entry.isFile() ? stat.size : 0,
      isDir: entry.isDirectory(),
      updatedAt: stat.mtime.toISOString(),
      extension: ext
    };
  }).sort((a, b) => (b.isDir ? 1 : 0) - (a.isDir ? 1 : 0) || a.name.localeCompare(b.name));
}

export function readServerFile(serverId: string, relPath: string): string {
  const baseDir = path.resolve(getServerDir(serverId));
  const rawTarget = path.resolve(baseDir, (relPath || '').replace(/\0/g, ''));
  if (rawTarget !== baseDir && !rawTarget.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  const targetPath = safePath(serverId, relPath);

  if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('File not found');
  }

  return fs.readFileSync(targetPath, 'utf-8');
}

export function writeServerFile(serverId: string, relPath: string, content: string): boolean {
  const baseDir = path.resolve(getServerDir(serverId));
  const rawTarget = path.resolve(baseDir, (relPath || '').replace(/\0/g, ''));
  if (rawTarget !== baseDir && !rawTarget.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  const targetPath = safePath(serverId, relPath);

  if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  const parentDir = path.dirname(targetPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, content, 'utf-8');
  return true;
}

export function deleteServerItem(serverId: string, relPath: string): void {
  const baseDir = path.resolve(getServerDir(serverId));
  const targetPath = safePath(serverId, relPath);

  if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied');
  }

  if (targetPath === baseDir) {
    throw new Error('Cannot delete server root directory');
  }

  if (fs.existsSync(targetPath)) {
    fs.rmSync(targetPath, { recursive: true, force: true });
  }
}

export function deleteServerItems(serverId: string, relPaths: string[]): {
  succeeded: string[];
  failed: Array<{ path: string; error: string }>;
} {
  const baseDir = path.resolve(getServerDir(serverId));
  const succeeded: string[] = [];
  const failed: Array<{ path: string; error: string }> = [];

  for (const rel of relPaths) {
    try {
      const targetPath = safePath(serverId, rel);
      if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
        failed.push({ path: rel, error: 'Access denied: outside root' });
        continue;
      }
      if (targetPath === baseDir) {
        failed.push({ path: rel, error: 'Cannot delete server root' });
        continue;
      }
      if (fs.existsSync(targetPath)) {
        fs.rmSync(targetPath, { recursive: true, force: true });
      }
      succeeded.push(rel);
    } catch (err: any) {
      failed.push({ path: rel, error: err.message || 'Deletion error' });
    }
  }

  return { succeeded, failed };
}

function getAvailablePath(targetPath: string): string {
  if (!fs.existsSync(targetPath)) return targetPath;
  const dir = path.dirname(targetPath);
  const ext = path.extname(targetPath);
  const base = path.basename(targetPath, ext);
  let counter = 1;
  while (fs.existsSync(path.join(dir, `${base} (${counter})${ext}`))) {
    counter++;
  }
  return path.join(dir, `${base} (${counter})${ext}`);
}

export function moveServerItems(
  serverId: string,
  sources: string[],
  destinationDir: string,
  conflictStrategy: 'replace' | 'rename' | 'skip' = 'replace'
): {
  moved: string[];
  skipped: string[];
  conflicts: string[];
  errors: Array<{ path: string; error: string }>;
} {
  const baseDir = path.resolve(getServerDir(serverId));
  const destDirPath = safePath(serverId, destinationDir);

  if (destDirPath !== baseDir && !destDirPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Destination is outside server root');
  }

  if (!fs.existsSync(destDirPath)) {
    fs.mkdirSync(destDirPath, { recursive: true });
  }

  const moved: string[] = [];
  const skipped: string[] = [];
  const conflicts: string[] = [];
  const errors: Array<{ path: string; error: string }> = [];

  for (const src of sources) {
    try {
      const srcPath = safePath(serverId, src);
      if (srcPath !== baseDir && !srcPath.startsWith(baseDir + path.sep)) {
        errors.push({ path: src, error: 'Access denied: Source is outside server root' });
        continue;
      }
      if (srcPath === baseDir) {
        errors.push({ path: src, error: 'Cannot move server root directory' });
        continue;
      }
      if (!fs.existsSync(srcPath)) {
        errors.push({ path: src, error: 'Source file does not exist' });
        continue;
      }

      // Check if moving folder inside itself
      if (destDirPath === srcPath || destDirPath.startsWith(srcPath + path.sep)) {
        errors.push({ path: src, error: 'Cannot move a folder into itself' });
        continue;
      }

      const itemName = path.basename(srcPath);
      let targetPath = path.join(destDirPath, itemName);

      if (fs.existsSync(targetPath)) {
        conflicts.push(src);
        if (conflictStrategy === 'skip') {
          skipped.push(src);
          continue;
        } else if (conflictStrategy === 'rename') {
          targetPath = getAvailablePath(targetPath);
        } else if (conflictStrategy === 'replace') {
          if (fs.statSync(targetPath).isDirectory()) {
            fs.rmSync(targetPath, { recursive: true, force: true });
          }
        }
      }

      fs.renameSync(srcPath, targetPath);
      moved.push(src);
    } catch (err: any) {
      errors.push({ path: src, error: err.message || 'Move error' });
    }
  }

  return { moved, skipped, conflicts, errors };
}

export function copyServerItems(
  serverId: string,
  sources: string[],
  destinationDir: string,
  conflictStrategy: 'replace' | 'rename' | 'skip' = 'replace'
): {
  copied: string[];
  skipped: string[];
  conflicts: string[];
  errors: Array<{ path: string; error: string }>;
} {
  const baseDir = path.resolve(getServerDir(serverId));
  const destDirPath = safePath(serverId, destinationDir);

  if (destDirPath !== baseDir && !destDirPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Destination is outside server root');
  }

  if (!fs.existsSync(destDirPath)) {
    fs.mkdirSync(destDirPath, { recursive: true });
  }

  const copied: string[] = [];
  const skipped: string[] = [];
  const conflicts: string[] = [];
  const errors: Array<{ path: string; error: string }> = [];

  for (const src of sources) {
    try {
      const srcPath = safePath(serverId, src);
      if (srcPath !== baseDir && !srcPath.startsWith(baseDir + path.sep)) {
        errors.push({ path: src, error: 'Access denied: Source is outside server root' });
        continue;
      }
      if (srcPath === baseDir) {
        errors.push({ path: src, error: 'Cannot copy server root directory' });
        continue;
      }
      if (!fs.existsSync(srcPath)) {
        errors.push({ path: src, error: 'Source file does not exist' });
        continue;
      }

      // Check if copying directory into itself
      if (destDirPath === srcPath || destDirPath.startsWith(srcPath + path.sep)) {
        errors.push({ path: src, error: 'Cannot copy a folder into itself' });
        continue;
      }

      const itemName = path.basename(srcPath);
      let targetPath = path.join(destDirPath, itemName);

      if (fs.existsSync(targetPath)) {
        conflicts.push(src);
        if (conflictStrategy === 'skip') {
          skipped.push(src);
          continue;
        } else if (conflictStrategy === 'rename') {
          targetPath = getAvailablePath(targetPath);
        } else if (conflictStrategy === 'replace') {
          if (fs.statSync(targetPath).isDirectory()) {
            fs.rmSync(targetPath, { recursive: true, force: true });
          }
        }
      }

      fs.cpSync(srcPath, targetPath, { recursive: true, force: true });
      copied.push(src);
    } catch (err: any) {
      errors.push({ path: src, error: err.message || 'Copy error' });
    }
  }

  return { copied, skipped, conflicts, errors };
}

export function createServerDirectory(serverId: string, relPath: string): void {
  const baseDir = path.resolve(getServerDir(serverId));
  const targetPath = safePath(serverId, relPath);

  if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(targetPath, { recursive: true });
  }
}

export function renameServerItem(serverId: string, oldRelPath: string, newRelPath: string): void {
  const baseDir = path.resolve(getServerDir(serverId));
  const oldPath = safePath(serverId, oldRelPath);
  const newPath = safePath(serverId, newRelPath);

  if ((oldPath !== baseDir && !oldPath.startsWith(baseDir + path.sep)) ||
      (newPath !== baseDir && !newPath.startsWith(baseDir + path.sep))) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(oldPath)) {
    throw new Error('Source file or folder does not exist');
  }

  const parent = path.dirname(newPath);
  if (!fs.existsSync(parent)) {
    fs.mkdirSync(parent, { recursive: true });
  }

  fs.renameSync(oldPath, newPath);
}

export function chmodServerItem(serverId: string, relPath: string, mode: number | string): void {
  const baseDir = path.resolve(getServerDir(serverId));
  const targetPath = safePath(serverId, relPath);

  if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('Target file or folder not found');
  }

  const numMode = typeof mode === 'string' ? parseInt(mode, 8) : mode;
  fs.chmodSync(targetPath, numMode);
}

export function compressServerItems(
  serverId: string,
  relPaths: string[],
  outputZipName?: string,
  currentDir: string = '/'
): string {
  const baseDir = path.resolve(getServerDir(serverId));
  const currentDirPath = safePath(serverId, currentDir);

  if (currentDirPath !== baseDir && !currentDirPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Outside server root');
  }

  const zip = new AdmZip();
  let itemsCount = 0;

  for (const rel of relPaths) {
    const targetPath = safePath(serverId, rel);
    if (targetPath !== baseDir && !targetPath.startsWith(baseDir + path.sep)) {
      continue;
    }
    if (!fs.existsSync(targetPath)) {
      continue;
    }

    const stat = fs.statSync(targetPath);
    const itemName = path.basename(targetPath);

    if (stat.isDirectory()) {
      zip.addLocalFolder(targetPath, itemName);
    } else {
      zip.addLocalFile(targetPath);
    }
    itemsCount++;
  }

  if (itemsCount === 0) {
    throw new Error('No valid files or folders found to compress');
  }

  const rawZipName = outputZipName?.trim()
    ? (outputZipName.endsWith('.zip') ? outputZipName.trim() : `${outputZipName.trim()}.zip`)
    : `archive_${Date.now()}.zip`;

  // Prevent path traversal in archive name
  const cleanZipName = path.basename(rawZipName);
  const zipPath = path.join(currentDirPath, cleanZipName);

  zip.writeZip(zipPath);
  return path.relative(baseDir, zipPath).replace(/\\/g, '/');
}

export function compressServerItem(serverId: string, relPath: string): string {
  return compressServerItems(serverId, [relPath], undefined, path.dirname(relPath));
}

// Secure Zip Decompression protecting against Zip Slip path traversal
export function decompressServerItem(serverId: string, zipRelPath: string, destinationDir?: string): void {
  const baseDir = path.resolve(getServerDir(serverId));
  const zipPath = safePath(serverId, zipRelPath);

  if (zipPath !== baseDir && !zipPath.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(zipPath)) {
    throw new Error('ZIP file not found');
  }

  const destDir = destinationDir
    ? safePath(serverId, destinationDir)
    : path.dirname(zipPath);

  if (destDir !== baseDir && !destDir.startsWith(baseDir + path.sep)) {
    throw new Error('Access denied: Destination is outside server root');
  }

  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  const zip = new AdmZip(zipPath);
  const zipEntries = zip.getEntries();

  for (const entry of zipEntries) {
    const entryPath = entry.entryName;
    const resolvedPath = path.resolve(destDir, entryPath);

    // Zip Slip check
    if (resolvedPath !== destDir && !resolvedPath.startsWith(destDir + path.sep)) {
      throw new Error(`Security Violation: Zip Slip detected in entry '${entryPath}'`);
    }

    if (entry.isDirectory) {
      fs.mkdirSync(resolvedPath, { recursive: true });
    } else {
      const parentDir = path.dirname(resolvedPath);
      if (!fs.existsSync(parentDir)) {
        fs.mkdirSync(parentDir, { recursive: true });
      }
      fs.writeFileSync(resolvedPath, entry.getData());
    }
  }
}

// Environment Variables (.env)
export function readServerEnv(serverId: string): Record<string, string> {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');
  const envMap: Record<string, string> = {};

  if (!fs.existsSync(envPath)) {
    return envMap;
  }

  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.substring(0, eqIdx).trim();
      const val = trimmed.substring(eqIdx + 1).trim();
      if (key) {
        envMap[key] = val;
      }
    }
  }

  return envMap;
}

export function writeServerEnv(serverId: string, envMap: Record<string, string>): void {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');

  const content = Object.entries(envMap)
    .map(([k, v]) => `${k.trim()}=${v}`)
    .join('\n');

  fs.writeFileSync(envPath, content, 'utf-8');
}

// Record Server Activity Audit
export async function recordServerActivity(
  serverId: string,
  userId: string,
  username: string,
  action: string,
  details: string
): Promise<ServerActivity> {
  const db = await getDb();
  const act: ServerActivity = {
    id: `act_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
    serverId,
    userId,
    username,
    action,
    details,
    createdAt: new Date().toISOString()
  };

  db.activities.unshift(act);
  saveDbSync();
  return act;
}

// Minecraft Plugins Helper
export interface MinecraftPluginInfo {
  filename: string;
  name: string;
  version?: string;
  size: number;
  isEnabled: boolean;
  updatedAt: string;
}

export function listMinecraftPlugins(serverId: string): MinecraftPluginInfo[] {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');

  if (!fs.existsSync(pluginsDir)) {
    fs.mkdirSync(pluginsDir, { recursive: true });
  }

  const files = fs.readdirSync(pluginsDir);
  const list: MinecraftPluginInfo[] = [];

  for (const f of files) {
    if (f.endsWith('.jar') || f.endsWith('.jar.disabled')) {
      const fullPath = path.join(pluginsDir, f);
      let stat = { size: 0, mtime: new Date() };
      try {
        stat = fs.statSync(fullPath);
      } catch (e) {}

      const isEnabled = !f.endsWith('.disabled');
      const cleanName = f.replace(/\.jar(\.disabled)?$/, '');

      list.push({
        filename: f,
        name: cleanName,
        version: '1.0.0',
        size: stat.size,
        isEnabled,
        updatedAt: stat.mtime.toISOString()
      });
    }
  }

  return list;
}

export function toggleMinecraftPlugin(serverId: string, filename: string): boolean {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');
  const currentPath = path.join(pluginsDir, filename);

  if (!fs.existsSync(currentPath)) {
    throw new Error('Plugin file not found');
  }

  if (filename.endsWith('.disabled')) {
    const newName = filename.replace(/\.disabled$/, '');
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return true; // Enabled
  } else if (filename.endsWith('.jar')) {
    const newName = `${filename}.disabled`;
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return false; // Disabled
  }

  return true;
}


