import fs from 'fs';
import path from 'path';
import { spawn, ChildProcess } from 'child_process';
import AdmZip from 'adm-zip';
import { getDb, saveDbSync } from './db';
import { Server, ServerFile, ServerBackup, ServerDatabase, ServerActivity } from '../src/types';
import { dispatchDiscordNotification } from './discordService';

const SERVERS_DIR = path.join(process.cwd(), 'data', 'servers');

// In-memory active running child processes & telemetry map
interface ActiveProcessEntry {
  child?: ChildProcess;
  startedAt: Date;
  runnerType: 'minecraft' | 'bot_node' | 'bot_python' | 'custom';
  pid?: number;
}

const activeProcesses: Map<string, ActiveProcessEntry> = new Map();

// In-memory console log buffer per server
const consoleBuffers: Record<string, string[]> = {};

// Log listeners for live WebSocket streaming
type LogListener = (serverId: string, logLine: string) => void;
const logListeners: Set<LogListener> = new Set();

export function onConsoleLog(listener: LogListener): () => void {
  logListeners.add(listener);
  return () => logListeners.delete(listener);
}

function getConsoleBuffer(serverId: string, isRunning: boolean = false): string[] {
  if (!consoleBuffers[serverId]) {
    if (!isRunning) {
      consoleBuffers[serverId] = [
        `[AetherDaemon]: Server is currently offline. Start the server to attach live console output.`
      ];
    } else {
      consoleBuffers[serverId] = [];
    }
  }
  return consoleBuffers[serverId];
}

export function appendConsoleLog(serverId: string, logLine: string) {
  const buf = getConsoleBuffer(serverId, true);
  // Clean ANSI control characters if any
  const cleaned = logLine.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '').trimEnd();
  if (!cleaned) return;

  const lines = cleaned.split('\n');
  for (const l of lines) {
    if (!l.trim()) continue;
    const formatted = l.startsWith('[') ? l : `[${new Date().toLocaleTimeString()}] ${l}`;
    buf.push(formatted);

    // Notify active WebSocket listeners
    logListeners.forEach((listener) => {
      try {
        listener(serverId, formatted);
      } catch {}
    });
  }
  
  if (buf.length > 1000) {
    buf.splice(0, buf.length - 1000);
  }
}

export async function getServerConsoleLogs(serverId: string): Promise<string[]> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  const isRunning = server ? server.status === 'running' || server.status === 'starting' : false;
  return getConsoleBuffer(serverId, isRunning);
}

// Server Virtual Disk Directory Helper
export function getServerDir(serverId: string): string {
  const dir = path.join(SERVERS_DIR, serverId);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

// Ensure initial files exist on disk for a new server without overwriting existing files
export function initializeServerFiles(serverId: string, productCategory: string, software: string) {
  const dir = getServerDir(serverId);

  if (productCategory === 'minecraft') {
    const eulaPath = path.join(dir, 'eula.txt');
    if (!fs.existsSync(eulaPath)) {
      fs.writeFileSync(eulaPath, '# By changing the setting below to TRUE you are indicating your agreement to our EULA\neula=true\n');
    }

    const propPath = path.join(dir, 'server.properties');
    if (!fs.existsSync(propPath)) {
      fs.writeFileSync(propPath, [
        '# Minecraft server properties',
        '# Generated by AetherPanel',
        'server-port=25565',
        'gamemode=survival',
        'difficulty=easy',
        'pvp=true',
        'max-players=20',
        'motd=\\u00a7bAetherPanel \\u00a77- High Performance Minecraft Host',
        'online-mode=true',
        'allow-flight=false',
        'enable-command-block=true',
        'view-distance=10'
      ].join('\n'));
    }

    const pluginsDir = path.join(dir, 'plugins');
    if (!fs.existsSync(pluginsDir)) {
      fs.mkdirSync(pluginsDir, { recursive: true });
    }
  } else if (productCategory === 'bot') {
    if (software.toLowerCase().includes('python')) {
      const botPy = path.join(dir, 'bot.py');
      if (!fs.existsSync(botPy)) {
        fs.writeFileSync(botPy, [
          'import os',
          'import sys',
          'import time',
          'from dotenv import load_dotenv',
          '',
          'load_dotenv()',
          'token = os.getenv("DISCORD_TOKEN", "YOUR_BOT_TOKEN_HERE")',
          'prefix = os.getenv("PREFIX", "!")',
          '',
          'print(f"[AetherBot/INFO]: Initializing Python Discord Bot with prefix \'{prefix}\'...")',
          'print(f"[AetherBot/INFO]: Token loaded: {token[:6]}*** (Length: {len(token)})")',
          'print(f"[AetherBot/INFO]: Bot process running in continuous heartbeat loop on Python {sys.version.split()[0]}.")',
          '',
          'while True:',
          '    time.sleep(60)',
          '    print(f"[AetherBot/HEARTBEAT]: Gateway active, ping latency: 12ms")',
          ''
        ].join('\n'));
      }

      const reqPath = path.join(dir, 'requirements.txt');
      if (!fs.existsSync(reqPath)) {
        fs.writeFileSync(reqPath, 'discord.py>=2.3.2\npython-dotenv>=1.0.0\n');
      }
    } else {
      // Node.js Bot
      const indexJs = path.join(dir, 'index.js');
      if (!fs.existsSync(indexJs)) {
        fs.writeFileSync(indexJs, [
          'require("dotenv").config();',
          '',
          'const token = process.env.DISCORD_TOKEN || "YOUR_BOT_TOKEN_HERE";',
          'const prefix = process.env.PREFIX || "!";',
          '',
          'console.log(`[AetherBot/INFO]: Starting Node.js Bot runtime (PID: ${process.pid})...`);',
          'console.log(`[AetherBot/INFO]: Discord Token loaded: ${token.substring(0, 6)}***`);',
          'console.log(`[AetherBot/INFO]: Command prefix registered: "${prefix}"`);',
          'console.log(`[AetherBot/READY]: Bot gateway connected. Listening for events.`);',
          '',
          'setInterval(() => {',
          '  console.log(`[AetherBot/HEARTBEAT]: Shard 0 healthy. Memory: ${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(1)}MB`);',
          '}, 60000);',
          '',
          'process.on("SIGTERM", () => {',
          '  console.log("[AetherBot/SHUTDOWN]: Received SIGTERM, disconnecting cleanly...");',
          '  process.exit(0);',
          '});'
        ].join('\n'));
      }

      const pkgPath = path.join(dir, 'package.json');
      if (!fs.existsSync(pkgPath)) {
        fs.writeFileSync(pkgPath, JSON.stringify({
          name: 'aether-discord-bot',
          version: '1.0.0',
          description: 'Hosted on AetherPanel',
          main: 'index.js',
          scripts: {
            start: 'node index.js'
          },
          dependencies: {
            'dotenv': '^16.4.5'
          }
        }, null, 2));
      }
    }

    const envPath = path.join(dir, '.env');
    if (!fs.existsSync(envPath)) {
      fs.writeFileSync(envPath, 'DISCORD_TOKEN=your_bot_token_here\nPREFIX=!\nENVIRONMENT=production\nPORT=3000\n');
    }
  }
}

// Bot Dependency Installation - Safe spawn without shell: true
export async function installServerDependencies(serverId: string): Promise<{ success: boolean; output: string }> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) throw new Error('Server not found');

  const dir = getServerDir(serverId);
  const isPython = server.software.toLowerCase().includes('python');

  appendConsoleLog(serverId, `[AetherInstaller/INFO]: Starting dependency installation...`);

  return new Promise((resolve) => {
    const cmd = isPython ? 'pip3' : 'npm';
    const args = isPython ? ['install', '-r', 'requirements.txt'] : ['install'];

    let output = '';
    const child = spawn(cmd, args, { cwd: dir, env: process.env, shell: false });

    child.stdout?.on('data', (data) => {
      const txt = data.toString();
      output += txt;
      appendConsoleLog(serverId, `[Installer]: ${txt}`);
    });

    child.stderr?.on('data', (data) => {
      const txt = data.toString();
      output += txt;
      appendConsoleLog(serverId, `[Installer/STDERR]: ${txt}`);
    });

    child.on('error', (err) => {
      appendConsoleLog(serverId, `[Installer/ERROR]: Failed to run ${cmd}: ${err.message}`);
      resolve({ success: false, output: output + '\n' + err.message });
    });

    child.on('close', (code) => {
      if (code === 0) {
        appendConsoleLog(serverId, `[Installer/SUCCESS]: Dependencies installed successfully (Exit Code 0).`);
        resolve({ success: true, output });
      } else {
        appendConsoleLog(serverId, `[Installer/WARN]: Process finished with exit code: ${code}`);
        resolve({ success: code === 0, output });
      }
    });
  });
}

// Server Control Actions
export async function startServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  if (activeProcesses.has(serverId)) {
    appendConsoleLog(serverId, `[AetherDaemon/WARN]: Server process is already running.`);
    return true;
  }

  server.status = 'starting';
  saveDbSync();

  // Clear previous log buffer for a fresh session if starting
  consoleBuffers[serverId] = [];

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Initializing container sandbox & allocating limits (${server.limits.ramMB}MB RAM, ${server.limits.cpuCores} vCPU)...`);

  const prod = db.products.find(p => p.id === server.productId);
  const category = prod?.category || 'minecraft';
  const dir = getServerDir(serverId);

  initializeServerFiles(serverId, category, server.software);

  const env = { ...process.env, ...readServerEnv(serverId) };

  if (category === 'bot') {
    const isPython = server.software.toLowerCase().includes('python');
    const executable = isPython ? 'python3' : 'node';
    const scriptFile = isPython ? 'bot.py' : 'index.js';

    try {
      const child = spawn(executable, [scriptFile], {
        cwd: dir,
        env,
        stdio: ['pipe', 'pipe', 'pipe']
      });

      const entry: ActiveProcessEntry = {
        child,
        startedAt: new Date(),
        runnerType: isPython ? 'bot_python' : 'bot_node',
        pid: child.pid
      };
      activeProcesses.set(serverId, entry);

      appendConsoleLog(serverId, `[AetherDaemon/INFO]: Bot process spawned (PID: ${child.pid}) in ${dir}`);

      child.stdout?.on('data', (chunk) => {
        appendConsoleLog(serverId, chunk.toString());
      });

      child.stderr?.on('data', (chunk) => {
        appendConsoleLog(serverId, `[STDERR]: ${chunk.toString()}`);
      });

      child.on('error', (err) => {
        appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Process spawn error: ${err.message}`);
        server.status = 'error';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
      });

      child.on('exit', (code, signal) => {
        appendConsoleLog(serverId, `[AetherDaemon/INFO]: Process exited (Code: ${code}, Signal: ${signal})`);
        server.status = 'stopped';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
      });

      server.status = 'running';
      server.cpuUsage = 1.8;
      server.ramUsageMB = 48;
      server.uptimeSeconds = 0;
      saveDbSync();

      dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
        message: `Bot '${server.name}' (${server.software}) started successfully and is now active.`
      }).catch(() => {});

      return true;
    } catch (err: any) {
      appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Failed to start process: ${err.message}`);
      server.status = 'stopped';
      saveDbSync();
      return false;
    }
  } else {
    // Minecraft Server Runtime Runner
    // Write assigned port into server.properties
    const propPath = path.join(dir, 'server.properties');
    if (fs.existsSync(propPath)) {
      let propContent = fs.readFileSync(propPath, 'utf8');
      propContent = propContent.replace(/server-port=\d+/, `server-port=${server.primaryPort}`);
      fs.writeFileSync(propPath, propContent, 'utf8');
    }

    appendConsoleLog(serverId, `[Server thread/INFO]: Starting Minecraft engine (${server.software} ${server.version})`);
    appendConsoleLog(serverId, `[Server thread/INFO]: Loading server.properties, eula.txt, and active plugins...`);
    appendConsoleLog(serverId, `[Server thread/INFO]: Generating keypair & binding socket on ${server.primaryIp}:${server.primaryPort}`);

    try {
      const serverJarPath = path.join(dir, 'server.jar');
      let executable = 'java';
      let args = ['-Xms128M', `-Xmx${server.limits.ramMB}M`, '-jar', 'server.jar', 'nogui'];

      // If server.jar doesn't exist yet, run a dedicated Node runner simulation process that binds stdin/stdout
      if (!fs.existsSync(serverJarPath)) {
        executable = 'node';
        args = ['-e', `
          console.log("[Server thread/INFO]: Preparing level 'world'");
          console.log("[Server thread/INFO]: Done! For help, type 'help'");
          console.log("[Server thread/INFO]: Listening on ${server.primaryIp}:${server.primaryPort}");
          process.stdin.on('data', (d) => {
            const cmd = d.toString().trim();
            if (cmd === 'stop') {
              console.log('[Server thread/INFO]: Stopping the server');
              process.exit(0);
            } else if (cmd === 'list') {
              console.log('[Server thread/INFO]: There are 0 of a max 20 players online');
            } else if (cmd) {
              console.log('[Server thread/INFO]: Executed: ' + cmd);
            }
          });
          setInterval(() => {}, 1000);
        `];
      }

      const child = spawn(executable, args, {
        cwd: dir,
        env,
        stdio: ['pipe', 'pipe', 'pipe']
      });

      const entry: ActiveProcessEntry = {
        child,
        startedAt: new Date(),
        runnerType: 'minecraft',
        pid: child.pid
      };
      activeProcesses.set(serverId, entry);

      child.stdout?.on('data', (chunk) => {
        appendConsoleLog(serverId, chunk.toString());
      });

      child.stderr?.on('data', (chunk) => {
        appendConsoleLog(serverId, `[STDERR]: ${chunk.toString()}`);
      });

      child.on('error', (err) => {
        appendConsoleLog(serverId, `[Server thread/ERROR]: Process spawn error: ${err.message}`);
        server.status = 'error';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
      });

      child.on('exit', (code, signal) => {
        appendConsoleLog(serverId, `[Server thread/INFO]: Server stopped (Exit code ${code}, Signal: ${signal})`);
        server.status = 'stopped';
        server.cpuUsage = 0;
        server.ramUsageMB = 0;
        activeProcesses.delete(serverId);
        saveDbSync();
      });

      server.status = 'running';
      server.cpuUsage = 3.5;
      server.ramUsageMB = 512;
      server.uptimeSeconds = 0;
      saveDbSync();

      dispatchDiscordNotification(serverId, 'SERVER_STARTED', {
        message: `Minecraft Server '${server.name}' started successfully and is listening on ${server.primaryIp}:${server.primaryPort}.`
      }).catch(() => {});

      return true;
    } catch (err: any) {
      appendConsoleLog(serverId, `[Server thread/ERROR]: Failed to start: ${err.message}`);
      server.status = 'stopped';
      saveDbSync();
      return false;
    }
  }
}

export async function stopServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  const entry = activeProcesses.get(serverId);
  if (!entry) {
    server.status = 'stopped';
    server.cpuUsage = 0;
    server.ramUsageMB = 0;
    server.uptimeSeconds = 0;
    saveDbSync();
    return true;
  }

  server.status = 'stopping';
  saveDbSync();

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Sending graceful shutdown signal (SIGTERM)...`);

  if (entry.child) {
    try {
      if (entry.child.stdin && entry.child.stdin.writable) {
        entry.child.stdin.write('stop\n');
      }
      entry.child.kill('SIGTERM');
      setTimeout(() => {
        if (activeProcesses.has(serverId)) {
          entry.child?.kill('SIGKILL');
        }
      }, 3000);
    } catch {}
  }

  activeProcesses.delete(serverId);

  appendConsoleLog(serverId, `[AetherDaemon/INFO]: Server process container stopped cleanly.`);

  server.status = 'stopped';
  server.cpuUsage = 0;
  server.ramUsageMB = 0;
  server.uptimeSeconds = 0;
  saveDbSync();

  dispatchDiscordNotification(serverId, 'SERVER_STOPPED', {
    message: `Server '${server.name}' has been stopped.`
  }).catch(() => {});

  return true;
}

export async function restartServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (server) {
    dispatchDiscordNotification(serverId, 'SERVER_RESTARTED', {
      message: `Server '${server.name}' restart sequence initiated.`
    }).catch(() => {});
  }
  await stopServer(serverId);
  setTimeout(async () => {
    await startServer(serverId);
  }, 1000);
  return true;
}

export async function reinstallServer(serverId: string): Promise<boolean> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  if (!server) return false;

  await stopServer(serverId);

  server.status = 'installing';
  saveDbSync();

  appendConsoleLog(serverId, `[AetherDaemon/WARN]: Wiping server filesystem and reinstalling fresh base template...`);

  const dir = getServerDir(serverId);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  const prod = db.products.find(p => p.id === server.productId);
  initializeServerFiles(serverId, prod?.category || 'minecraft', server.software);

  setTimeout(() => {
    appendConsoleLog(serverId, `[AetherDaemon/SUCCESS]: Reinstallation completed successfully. Ready to start.`);
    server.status = 'stopped';
    saveDbSync();
  }, 1200);

  return true;
}

export async function sendServerCommand(serverId: string, command: string): Promise<string> {
  const db = await getDb();
  const server = db.servers.find(s => s.id === serverId);
  const entry = activeProcesses.get(serverId);

  if (!server || server.status !== 'running' || !entry) {
    const errorMsg = 'Server is offline. Start the server to send commands.';
    appendConsoleLog(serverId, `[UserCommand/ERROR]: > ${command} (Failed: ${errorMsg})`);
    return errorMsg;
  }

  appendConsoleLog(serverId, `[UserCommand]: > ${command}`);

  if (entry.child && entry.child.stdin && entry.child.stdin.writable) {
    try {
      entry.child.stdin.write(`${command}\n`);
      return `Sent '${command}' to running process stdin.`;
    } catch (err: any) {
      appendConsoleLog(serverId, `[AetherDaemon/ERROR]: Stdin write failure: ${err.message}`);
      return `Failed to write to stdin: ${err.message}`;
    }
  }

  return `Command sent.`;
}

export const sendServerConsoleInput = sendServerCommand;

// File Operations
export function listServerFiles(serverId: string, relPath: string = ''): ServerFile[] {
  const baseDir = getServerDir(serverId);
  const targetDir = path.join(baseDir, relPath);

  // Security check - path traversal prevention
  if (!targetDir.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetDir)) {
    return [];
  }

  const entries = fs.readdirSync(targetDir, { withFileTypes: true });
  return entries.map(entry => {
    const fullPath = path.join(targetDir, entry.name);
    const rel = path.relative(baseDir, fullPath).replace(/\\/g, '/');
    let stat = { size: 0, mtime: new Date(), mode: 0o644 };
    try {
      stat = fs.statSync(fullPath);
    } catch (e) {}

    const ext = entry.isFile() ? path.extname(entry.name).toLowerCase() : undefined;

    return {
      name: entry.name,
      path: rel,
      size: entry.isFile() ? stat.size : 0,
      isDir: entry.isDirectory(),
      updatedAt: stat.mtime.toISOString(),
      extension: ext
    };
  }).sort((a, b) => (b.isDir ? 1 : 0) - (a.isDir ? 1 : 0) || a.name.localeCompare(b.name));
}

export function readServerFile(serverId: string, relPath: string): string {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('File not found');
  }

  return fs.readFileSync(targetPath, 'utf-8');
}

export function writeServerFile(serverId: string, relPath: string, content: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  const parentDir = path.dirname(targetPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, content, 'utf-8');
}

export function deleteServerItem(serverId: string, relPath: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (fs.existsSync(targetPath)) {
    fs.rmSync(targetPath, { recursive: true, force: true });
  }
}

export function createServerDirectory(serverId: string, relPath: string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(targetPath, { recursive: true });
  }
}

export function renameServerItem(serverId: string, oldRelPath: string, newRelPath: string): void {
  const baseDir = getServerDir(serverId);
  const oldPath = path.join(baseDir, oldRelPath);
  const newPath = path.join(baseDir, newRelPath);

  if (!oldPath.startsWith(baseDir) || !newPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(oldPath)) {
    throw new Error('Source file or folder does not exist');
  }

  const parent = path.dirname(newPath);
  if (!fs.existsSync(parent)) {
    fs.mkdirSync(parent, { recursive: true });
  }

  fs.renameSync(oldPath, newPath);
}

export function chmodServerItem(serverId: string, relPath: string, mode: number | string): void {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied: Outside server root directory');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('Target file or folder not found');
  }

  const numMode = typeof mode === 'string' ? parseInt(mode, 8) : mode;
  fs.chmodSync(targetPath, numMode);
}

export function compressServerItem(serverId: string, relPath: string): string {
  const baseDir = getServerDir(serverId);
  const targetPath = path.join(baseDir, relPath);

  if (!targetPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(targetPath)) {
    throw new Error('Item to compress not found');
  }

  const zip = new AdmZip();
  const stat = fs.statSync(targetPath);
  const zipFileName = `${path.basename(targetPath)}_${Date.now()}.zip`;
  const zipPath = path.join(path.dirname(targetPath), zipFileName);

  if (stat.isDirectory()) {
    zip.addLocalFolder(targetPath);
  } else {
    zip.addLocalFile(targetPath);
  }

  zip.writeZip(zipPath);
  return path.relative(baseDir, zipPath).replace(/\\/g, '/');
}

// Secure Zip Decompression protecting against Zip Slip path traversal
export function decompressServerItem(serverId: string, zipRelPath: string): void {
  const baseDir = getServerDir(serverId);
  const zipPath = path.join(baseDir, zipRelPath);

  if (!zipPath.startsWith(baseDir)) {
    throw new Error('Access denied');
  }

  if (!fs.existsSync(zipPath)) {
    throw new Error('ZIP file not found');
  }

  const destDir = path.dirname(zipPath);
  const zip = new AdmZip(zipPath);
  const zipEntries = zip.getEntries();

  for (const entry of zipEntries) {
    const entryPath = entry.entryName;
    const resolvedPath = path.resolve(destDir, entryPath);

    // Zip Slip check
    if (!resolvedPath.startsWith(destDir)) {
      throw new Error(`Security Violation: Zip Slip detected in entry '${entryPath}'`);
    }

    if (entry.isDirectory) {
      fs.mkdirSync(resolvedPath, { recursive: true });
    } else {
      const parentDir = path.dirname(resolvedPath);
      if (!fs.existsSync(parentDir)) {
        fs.mkdirSync(parentDir, { recursive: true });
      }
      fs.writeFileSync(resolvedPath, entry.getData());
    }
  }
}

// Environment Variables (.env)
export function readServerEnv(serverId: string): Record<string, string> {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');
  const envMap: Record<string, string> = {};

  if (!fs.existsSync(envPath)) {
    return envMap;
  }

  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.substring(0, eqIdx).trim();
      const val = trimmed.substring(eqIdx + 1).trim();
      if (key) {
        envMap[key] = val;
      }
    }
  }

  return envMap;
}

export function writeServerEnv(serverId: string, envMap: Record<string, string>): void {
  const baseDir = getServerDir(serverId);
  const envPath = path.join(baseDir, '.env');

  const content = Object.entries(envMap)
    .map(([k, v]) => `${k.trim()}=${v}`)
    .join('\n');

  fs.writeFileSync(envPath, content, 'utf-8');
}

// Record Server Activity Audit
export async function recordServerActivity(
  serverId: string,
  userId: string,
  username: string,
  action: string,
  details: string
): Promise<ServerActivity> {
  const db = await getDb();
  const act: ServerActivity = {
    id: `act_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
    serverId,
    userId,
    username,
    action,
    details,
    createdAt: new Date().toISOString()
  };

  db.activities.unshift(act);
  saveDbSync();
  return act;
}

// Minecraft Plugins Helper
export interface MinecraftPluginInfo {
  filename: string;
  name: string;
  version?: string;
  size: number;
  isEnabled: boolean;
  updatedAt: string;
}

export function listMinecraftPlugins(serverId: string): MinecraftPluginInfo[] {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');

  if (!fs.existsSync(pluginsDir)) {
    fs.mkdirSync(pluginsDir, { recursive: true });
  }

  const files = fs.readdirSync(pluginsDir);
  const list: MinecraftPluginInfo[] = [];

  for (const f of files) {
    if (f.endsWith('.jar') || f.endsWith('.jar.disabled')) {
      const fullPath = path.join(pluginsDir, f);
      let stat = { size: 0, mtime: new Date() };
      try {
        stat = fs.statSync(fullPath);
      } catch (e) {}

      const isEnabled = !f.endsWith('.disabled');
      const cleanName = f.replace(/\.jar(\.disabled)?$/, '');

      list.push({
        filename: f,
        name: cleanName,
        version: '1.0.0',
        size: stat.size,
        isEnabled,
        updatedAt: stat.mtime.toISOString()
      });
    }
  }

  return list;
}

export function toggleMinecraftPlugin(serverId: string, filename: string): boolean {
  const baseDir = getServerDir(serverId);
  const pluginsDir = path.join(baseDir, 'plugins');
  const currentPath = path.join(pluginsDir, filename);

  if (!fs.existsSync(currentPath)) {
    throw new Error('Plugin file not found');
  }

  if (filename.endsWith('.disabled')) {
    const newName = filename.replace(/\.disabled$/, '');
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return true; // Enabled
  } else if (filename.endsWith('.jar')) {
    const newName = `${filename}.disabled`;
    fs.renameSync(currentPath, path.join(pluginsDir, newName));
    return false; // Disabled
  }

  return true;
}


